// Данные по умолчанию для свежей установки — вынесены из useStore.ts (чистые данные).
import type {
  User,
  BarCategoryConfig,
  BarMenuItem,
  AppSettings,
  BilliardTable,
} from "../types";
import { hashPassword } from "./helpers";

// ===== ПОЛЬЗОВАТЕЛИ ПО УМОЛЧАНИЮ =====
export const defaultUsers: User[] = [
  {
    id: "dev-001",
    username: "developer",
    password: hashPassword("dev2026"),
    displayName: "Разработчик",
    role: "developer",
    createdAt: Date.now(),
    createdBy: null,
    isActive: true,
  },
  {
    id: "admin-001",
    username: "admin",
    password: hashPassword("admin2026"),
    displayName: "Администратор",
    role: "admin",
    createdAt: Date.now(),
    createdBy: null,
    isActive: true,
  },
];

// Изображение товара по ключевому слову (детерминированное, с интернета).
// Оператор может заменить на своё фото в разделе «Меню».
const kImg = (keyword: string, lock: number): string =>
  `https://loremflickr.com/300/300/${keyword}?lock=${lock}`;

// ===== КАТЕГОРИИ ПО УМОЛЧАНИЮ =====
// Бар: напитки, алкоголь, снэки, кальян
const defaultBarOnlyCategories: BarCategoryConfig[] = [
  {
    id: "drinks",
    name: "Напитки",
    icon: "Coffee",
    color: "#3b82f6",
    sortOrder: 0,
    department: "bar",
  },
  {
    id: "alcohol",
    name: "Алкоголь",
    icon: "Wine",
    color: "#a855f7",
    sortOrder: 1,
    department: "bar",
  },
  {
    id: "snacks",
    name: "Закуски",
    icon: "Sandwich",
    color: "#f59e0b",
    sortOrder: 2,
    department: "bar",
  },
  {
    id: "hookah",
    name: "Кальян",
    icon: "Wind",
    color: "#6366f1",
    sortOrder: 3,
    department: "bar",
  },
];

// Кухня: блюда (отдельный отдел, печатается на кухонном принтере)
const defaultKitchenCategories: BarCategoryConfig[] = [
  {
    id: "kitchen-hot",
    name: "Горячее",
    icon: "CircleDot",
    color: "#ef4444",
    sortOrder: 10,
    department: "kitchen",
  },
  {
    id: "kitchen-salads",
    name: "Салаты",
    icon: "Sandwich",
    color: "#10b981",
    sortOrder: 11,
    department: "kitchen",
  },
  {
    id: "kitchen-desserts",
    name: "Десерты",
    icon: "Coffee",
    color: "#ec4899",
    sortOrder: 12,
    department: "kitchen",
  },
];

export const defaultBarCategories: BarCategoryConfig[] = [
  ...defaultBarOnlyCategories,
  ...defaultKitchenCategories,
];

// Примеры блюд для кухни (можно удалить, добавить свои с фото и ценой)
const defaultKitchenMenu: BarMenuItem[] = [
  {
    id: "dish-1",
    name: "Цезарь с курицей",
    categoryId: "kitchen-salads",
    price: 1800,
    costPrice: 700,
    available: true,
    image: kImg("caesar-salad", 23),
    stock: -1,
    unit: "порц",
  },
  {
    id: "dish-2",
    name: "Стейк рибай",
    categoryId: "kitchen-hot",
    price: 4500,
    costPrice: 2000,
    available: true,
    image: kImg("steak", 24),
    stock: -1,
    unit: "порц",
  },
  {
    id: "dish-3",
    name: "Картофель фри",
    categoryId: "kitchen-hot",
    price: 1200,
    costPrice: 400,
    available: true,
    image: kImg("french-fries", 17),
    stock: -1,
    unit: "порц",
  },
  {
    id: "dish-4",
    name: "Бургер",
    categoryId: "kitchen-hot",
    price: 2200,
    costPrice: 900,
    available: true,
    image: kImg("burger", 27),
    stock: -1,
    unit: "порц",
  },
  {
    id: "dish-5",
    name: "Пицца Маргарита",
    categoryId: "kitchen-hot",
    price: 2800,
    costPrice: 1000,
    available: true,
    image: kImg("pizza", 26),
    stock: -1,
    unit: "порц",
  },
  {
    id: "dish-6",
    name: "Чизкейк",
    categoryId: "kitchen-desserts",
    price: 1500,
    costPrice: 500,
    available: true,
    image: kImg("cheesecake", 25),
    stock: -1,
    unit: "порц",
  },
];

// ===== МЕНЮ БАРА ПО УМОЛЧАНИЮ =====
export const defaultBarMenu: BarMenuItem[] = [
  // --- Напитки ---
  {
    id: "drink-1",
    name: "Эспрессо",
    categoryId: "drinks",
    price: 500,
    costPrice: 80,
    available: true,
    image: kImg("coffee", 1),
    stock: -1,
    unit: "шт",
  },
  {
    id: "drink-2",
    name: "Капучино",
    categoryId: "drinks",
    price: 700,
    costPrice: 120,
    available: true,
    image: kImg("cappuccino", 2),
    stock: -1,
    unit: "шт",
  },
  {
    id: "drink-3",
    name: "Латте",
    categoryId: "drinks",
    price: 800,
    costPrice: 140,
    available: true,
    image: kImg("coffee", 30),
    stock: -1,
    unit: "шт",
  },
  {
    id: "drink-4",
    name: "Американо",
    categoryId: "drinks",
    price: 600,
    costPrice: 90,
    available: true,
    image: kImg("coffee", 31),
    stock: -1,
    unit: "шт",
  },
  {
    id: "drink-5",
    name: "Чай чёрный",
    categoryId: "drinks",
    price: 300,
    costPrice: 50,
    available: true,
    image: kImg("tea", 3),
    stock: -1,
    unit: "шт",
  },
  {
    id: "drink-6",
    name: "Чай зелёный",
    categoryId: "drinks",
    price: 300,
    costPrice: 50,
    available: true,
    image: kImg("tea", 32),
    stock: -1,
    unit: "шт",
  },
  {
    id: "drink-7",
    name: "Coca-Cola 0.5",
    categoryId: "drinks",
    price: 600,
    costPrice: 200,
    available: true,
    image: kImg("cola", 21),
    stock: 24,
    unit: "шт",
  },
  {
    id: "drink-8",
    name: "Pepsi 0.5",
    categoryId: "drinks",
    price: 600,
    costPrice: 200,
    available: true,
    image: kImg("cola", 33),
    stock: 24,
    unit: "шт",
  },
  {
    id: "drink-9",
    name: "Sprite 0.5",
    categoryId: "drinks",
    price: 600,
    costPrice: 200,
    available: true,
    image: kImg("soda", 22),
    stock: 24,
    unit: "шт",
  },
  {
    id: "drink-10",
    name: "Fanta 0.5",
    categoryId: "drinks",
    price: 600,
    costPrice: 200,
    available: true,
    image: kImg("soda", 34),
    stock: 24,
    unit: "шт",
  },
  {
    id: "drink-11",
    name: "Сок апельсиновый",
    categoryId: "drinks",
    price: 500,
    costPrice: 150,
    available: true,
    image: kImg("orange-juice", 5),
    stock: 12,
    unit: "шт",
  },
  {
    id: "drink-12",
    name: "Вода 0.5",
    categoryId: "drinks",
    price: 200,
    costPrice: 50,
    available: true,
    image: kImg("water-bottle", 4),
    stock: 48,
    unit: "шт",
  },
  {
    id: "drink-13",
    name: "Red Bull",
    categoryId: "drinks",
    price: 900,
    costPrice: 400,
    available: true,
    image: kImg("energy-drink", 6),
    stock: 18,
    unit: "шт",
  },
  {
    id: "drink-14",
    name: "Лимонад",
    categoryId: "drinks",
    price: 700,
    costPrice: 250,
    available: true,
    image: kImg("lemonade", 7),
    stock: -1,
    unit: "шт",
  },
  {
    id: "drink-15",
    name: "Молочный коктейль",
    categoryId: "drinks",
    price: 1100,
    costPrice: 400,
    available: true,
    image: kImg("milkshake", 8),
    stock: -1,
    unit: "шт",
  },
  // --- Алкоголь ---
  {
    id: "alco-1",
    name: "Пиво разливное 0.5",
    categoryId: "alcohol",
    price: 800,
    costPrice: 300,
    available: true,
    image: kImg("beer", 9),
    stock: -1,
    unit: "шт",
  },
  {
    id: "alco-2",
    name: "Heineken 0.5",
    categoryId: "alcohol",
    price: 1000,
    costPrice: 450,
    available: true,
    image: kImg("beer", 35),
    stock: 24,
    unit: "шт",
  },
  {
    id: "alco-3",
    name: "Corona 0.33",
    categoryId: "alcohol",
    price: 1100,
    costPrice: 500,
    available: true,
    image: kImg("beer", 36),
    stock: 24,
    unit: "шт",
  },
  {
    id: "alco-4",
    name: "Вино красное (бокал)",
    categoryId: "alcohol",
    price: 1200,
    costPrice: 400,
    available: true,
    image: kImg("wine", 10),
    stock: -1,
    unit: "шт",
  },
  {
    id: "alco-5",
    name: "Вино белое (бокал)",
    categoryId: "alcohol",
    price: 1200,
    costPrice: 400,
    available: true,
    image: kImg("wine", 37),
    stock: -1,
    unit: "шт",
  },
  {
    id: "alco-6",
    name: "Виски Jack Daniel's 50мл",
    categoryId: "alcohol",
    price: 1800,
    costPrice: 700,
    available: true,
    image: kImg("whiskey", 11),
    stock: -1,
    unit: "мл",
  },
  {
    id: "alco-7",
    name: "Водка 50мл",
    categoryId: "alcohol",
    price: 600,
    costPrice: 150,
    available: true,
    image: kImg("vodka", 12),
    stock: -1,
    unit: "мл",
  },
  {
    id: "alco-8",
    name: "Мохито",
    categoryId: "alcohol",
    price: 1500,
    costPrice: 500,
    available: true,
    image: kImg("cocktail", 13),
    stock: -1,
    unit: "шт",
  },
  // --- Закуски ---
  {
    id: "snack-1",
    name: "Чипсы Lay's",
    categoryId: "snacks",
    price: 500,
    costPrice: 200,
    available: true,
    image: kImg("potato-chips", 14),
    stock: 20,
    unit: "шт",
  },
  {
    id: "snack-2",
    name: "Pringles",
    categoryId: "snacks",
    price: 900,
    costPrice: 450,
    available: true,
    image: kImg("potato-chips", 38),
    stock: 12,
    unit: "шт",
  },
  {
    id: "snack-3",
    name: "Орешки солёные",
    categoryId: "snacks",
    price: 500,
    costPrice: 200,
    available: true,
    image: kImg("nuts", 15),
    stock: 15,
    unit: "шт",
  },
  {
    id: "snack-4",
    name: "Попкорн",
    categoryId: "snacks",
    price: 600,
    costPrice: 200,
    available: true,
    image: kImg("popcorn", 16),
    stock: -1,
    unit: "шт",
  },
  {
    id: "snack-5",
    name: "Начос с сыром",
    categoryId: "snacks",
    price: 1200,
    costPrice: 450,
    available: true,
    image: kImg("nachos", 18),
    stock: -1,
    unit: "порц",
  },
  {
    id: "snack-6",
    name: "Сухарики",
    categoryId: "snacks",
    price: 300,
    costPrice: 100,
    available: true,
    image: kImg("potato-chips", 39),
    stock: 25,
    unit: "шт",
  },
  {
    id: "snack-7",
    name: "Snickers",
    categoryId: "snacks",
    price: 400,
    costPrice: 180,
    available: true,
    image: kImg("chocolate", 19),
    stock: 30,
    unit: "шт",
  },
  // --- Кальян ---
  {
    id: "hookah-1",
    name: "Кальян классический",
    categoryId: "hookah",
    price: 3000,
    costPrice: 800,
    available: true,
    image: kImg("hookah", 20),
    stock: -1,
    unit: "шт",
  },
  {
    id: "hookah-2",
    name: "Кальян фруктовый",
    categoryId: "hookah",
    price: 3500,
    costPrice: 1000,
    available: true,
    image: kImg("hookah", 40),
    stock: -1,
    unit: "шт",
  },
  {
    id: "hookah-3",
    name: "Доп. угли",
    categoryId: "hookah",
    price: 300,
    costPrice: 50,
    available: true,
    image: "",
    stock: 30,
    unit: "шт",
  },
  ...defaultKitchenMenu,
];

// ===== НАСТРОЙКИ ПО УМОЛЧАНИЮ =====
export const defaultSettings: AppSettings = {
  language: "ru",
  lastSeenVersion: "",
  sidebarPinned: ["dashboard", "bar", "reports", "settings"],
  userVisiblePages: ["dashboard", "bar", "kitchen", "reports", "settings"],
  tablesViewMode: "grid",
  clubName: "Бильярдный Клуб",
  receiptCompanyName: "ИП Coffee Time",
  receiptCity: "г. Шымкент",
  receiptPhone: "+7 777 123 45 67",
  receiptCashierName: "ИМЯ",
  defaultPricePerHour: 2000,
  currency: "тг",
  theme: "dark",
  autoLightOff: true,
  soundEnabled: true,
  autoPrintReceipt: false,
  silentPrint: true,
  savedPortPath: null,
  receiptWidthMm: 80,
  receiptFontSize: 14,
  receiptPaddingMm: 5,
  serviceChargeEnabled: false,
  serviceChargePercent: 10,
  kitchenSeparate: false,
  autoPrintKitchenTicket: true,
  personnelEnabled: false,
  receiptPrinterName: "",
  kitchenPrinterName: "",
  tables: [
    {
      id: 1,
      name: "Стол №1",
      relayNumber: 1,
      pricePerHour: 2000,
      priceSchedule: [],
      isActive: true,
    },
    {
      id: 2,
      name: "Стол №2",
      relayNumber: 2,
      pricePerHour: 2000,
      priceSchedule: [],
      isActive: true,
    },
    {
      id: 3,
      name: "Стол №3",
      relayNumber: 3,
      pricePerHour: 2500,
      priceSchedule: [],
      isActive: true,
    },
    {
      id: 4,
      name: "Стол №4",
      relayNumber: 4,
      pricePerHour: 2500,
      priceSchedule: [],
      isActive: true,
    },
  ],
};

// ===== СТОЛЫ ПО УМОЛЧАНИЮ =====
export const defaultTables: BilliardTable[] = defaultSettings.tables.map(
  (t) => ({
    id: t.id,
    name: t.name,
    relayNumber: t.relayNumber,
    status: "free" as const,
    lightOn: false,
    pricePerHour: t.pricePerHour,
    priceSchedule: t.priceSchedule,
    currentSession: null,
  }),
);
